CREATE TABLE department (
	dept_id varchar2(10),
	dept_name varchar2(20) NOT NULL, 
	office varchar2(20),
	CONSTRAINT pk_department PRIMARY Key(dept_id)
)

CREATE TABLE student (
	stu_id varchar2(10),
	resident_id varchar2(14) NOT NULL,
	name varchar2(10) NOT NULL,
	YEAR int,
	address varchar2(10),
	dept_id varchar2(10),
	CONSTRAINT pk_student PRIMARY KEY(stu_id),
	CONSTRAINT fk_student FOREIGN key(dept_id)
	REFERENCES department(dept_id)
)

CREATE TABLE professor (
	prof_id varchar2(10),
	resident_id varchar2(14) NOT NULL,
	name varchar2(10) NOT NULL,
	dept_id varchar2(10),
	POSITION varchar2(10),
	year_emp int,
	CONSTRAINT pk_professor PRIMARY key(prof_id),
	CONSTRAINT fk_professor foreign key(dept_id)
		REFERENCES department(dept_id)
)

CREATE TABLE course (
	course_id varchar2(10),
	title varchar2(14) NOT NULL,
	credit int,
	CONSTRAINT pk_course PRIMARY key(course_id)
)

CREATE TABLE class (
	class_id varchar2(10),
	course_id varchar2(10),
	YEAR int,
	semester int,
	division char(1),
	prof_id varchar2(10),
	classroom varchar2(9),
	enroll int,
	CONSTRAINT pk_class PRIMARY key(class_id),
	CONSTRAINT fk_class1 FOREIGN key(course_id)
	REFERENCES course(course_id),
	CONSTRAINT fk_class2 FOREIGN key(prof_id)
	REFERENCES professor(prof_id)
)

CREATE TABLE takes (
	stu_id varchar2(10),
	class_id varchar2(10),
	grade char(5),
	CONSTRAINT pk_takes PRIMARY key(stu_id, class_id),
	CONSTRAINT fk_takes1 FOREIGN key(stu_id)
	REFERENCES student(stu_id),
	CONSTRAINT fk_takes2 FOREIGN key(class_id)
	REFERENCES class(class_id)
)

ALTER TABLE student
ADD age int

ALTER TABLE student
DROP COLUMN age

SELECT * FROM tab;

purge recyclebin;

-- 2026-04-07 -------------------------------------------
SELECT NAME 이름, POSITION AS 직위, 2026-YEAR_EMP 재직연수
FROM PROFESSOR

SELECT *
FROM STUDENT S1, STUDENT S2

SELECT S2.NAME
FROM STUDENT S1, STUDENT S2
WHERE S1.ADDRESS = S2.ADDRESS 
AND S1.NAME = '김광식'

SELECT *
FROM STUDENT
WHERE ADDRESS ='서울'

SELECT ADDRESS
FROM STUDENT
WHERE NAME='김광식'

SELECT S.NAME, D.DEPT_NAME
FROM STUDENT s, DEPARTMENT D
WHERE S.DEPT_ID = D.DEPT_ID 

SELECT NAME, STU_ID
FROM STUDENT
WHERE YEAR=3 OR YEAR=4
ORDER BY NAME desc, STU_ID

SELECT STUDENT.STU_ID, STUDENT.DEPT_ID
FROM STUDENT, DEPARTMENT
WHERE STUDENT.DEPT_ID = DEPARTMENT.DEPT_ID 
AND STUDENT.YEAR=3
AND DEPARTMENT.DEPT_NAME ='컴퓨터공학과'

SELECT NAME, DEPT_NAME
FROM STUDENT, DEPARTMENT
WHERE STUDENT.DEPT_ID =DEPARTMENT.DEPT_ID 

SELECT * FROM STUDENT

SELECT * FROM DEPARTMENT


SELECT STUDENT.NAME, STUDENT.STU_ID, DEPARTMENT.DEPT_NAME 
FROM STUDENT, DEPARTMENT
WHERE STUDENT.DEPT_ID =DEPARTMENT.DEPT_ID 

SELECT DEPT_ID, DEPT_NAME
FROM DEPARTMENT

SELECT NAME, STU_ID, DEPT_ID 
FROM STUDENT

SELECT NAME, 2026-YEAR_EMP
FROM PROFESSOR

SELECT RESIDENT_ID, STU_ID, NAME, YEAR
FROM STUDENT

SELECT DISTINCT ADDRESS
FROM STUDENT

SELECT * FROM DEPARTMENT

INSERT INTO STUDENT 
VALUES ('1292002', '900305*1730021', '강승진', 3, '서울', '921')

DELETE --SELECT *
FROM PROFESSOR
WHERE NAME ='김태석'

SELECT * FROM PROFESSOR

SELECT *
FROM STUDENT
WHERE NAME LIKE '김%'

SELECT *
FROM STUDENT
WHERE RESIDENT_ID LIKE '%*2%'
OR RESIDENT_ID LIKE '%*4%'

SELECT * FROM EMP

SELECT NAME FROM STUDENT
UNION ALL
SELECT NAME FROM PROFESSOR

-- 64PAGE
SELECT S.STU_ID
FROM STUDENT S, DEPARTMENT D, TAKES T
WHERE S.DEPT_ID =D.DEPT_ID 
AND T.STU_ID =S.STU_ID 
AND DEPT_NAME = '컴퓨터공학과'
AND GRADE ='A+'

SELECT STU_ID -- [1292001], 1292002, [1292003]
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPT_ID =D.DEPT_ID 
AND D.DEPT_NAME ='컴퓨터공학과'
INTERSECT 
SELECT STU_ID	-- [1292001], [1292003], 1292303
FROM TAKES
WHERE GRADE='A+'

SELECT STU_ID	-- 1292301, [1292303], 1292305
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPT_ID =D.DEPT_ID 
AND D.DEPT_NAME ='산업공학과'
MINUS
SELECT STU_ID	-- 1292001, 1292003, [1292303]
FROM TAKES
WHERE GRADE='A+'

SELECT * FROM COURSE

SELECT * FROM CLASS

SELECT TITLE, CREDIT, YEAR, SEMESTER, DIVISION
FROM COURSE, CLASS
WHERE COURSE.COURSE_ID = CLASS.COURSE_ID 

SELECT TITLE, CREDIT, YEAR, SEMESTER, DIVISION
FROM COURSE LEFT OUTER JOIN CLASS
USING(COURSE_ID)

SELECT TITLE, CREDIT, YEAR, SEMESTER
FROM COURSE, CLASS
WHERE COURSE.COURSE_ID =CLASS.COURSE_ID (+)

SELECT TITLE, CREDIT, YEAR, SEMESTER
FROM COURSE RIGHT OUTER JOIN CLASS
USING(COURSE_ID)

SELECT TITLE, CREDIT, YEAR, SEMESTER
FROM COURSE, CLASS
WHERE COURSE.COURSE_ID (+) = CLASS.COURSE_ID 

SELECT TITLE, CREDIT, YEAR, SEMESTER
FROM COURSE FULL OUTER JOIN CLASS
USING (COURSE_ID)

SELECT COUNT(*)
FROM STUDENT
WHERE YEAR=3

SELECT * --COUNT(*)
FROM EMP

SELECT COUNT(COMM)
FROM EMP

SELECT COUNT(DEPT_ID)
FROM STUDENT

SELECT COUNT(DISTINCT DEPT_ID)
FROM STUDENT

SELECT COUNT(*)
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPT_ID =D.DEPT_ID 
AND D.DEPT_NAME ='컴퓨터공학과'

SELECT 2026-YEAR_EMP
FROM PROFESSOR

INSERT INTO PROFESSOR 
   values('92302','750728*1102458','김태석',923,'교수',1999);

SELECT * FROM EMP

SELECT * FROM DEPT

SELECT ENAME, DNAME, LOC
FROM EMP, DEPT
WHERE EMP.DEPTNO =DEPT.DEPTNO

SELECT SUM(SAL)
FROM EMP

SELECT SUM(SAL)
FROM EMP
WHERE JOB='ANALYST'

SELECT SUM(SAL)
FROM EMP E, DEPT D
WHERE E.DEPTNO =D.DEPTNO 
AND DNAME='RESEARCH'

SELECT AVG(2026-YEAR_EMP)
FROM PROFESSOR

SELECT COUNT(SAL), MAX(SAL), MIN(SAL), AVG(SAL)
FROM EMP E, DEPT D
WHERE E.DEPTNO =D.DEPTNO 
AND DNAME='ACCOUNTING'

SELECT *
FROM EMP E

SELECT *
FROM PROFESSOR


WHERE E.ENAME ='SMITH' 

SELECT ENAME, MAX(SAL)
FROM EMP

SELECT DEPT_ID, COUNT(*)
FROM STUDENT
GROUP BY DEPT_ID

SELECT DEPT_NAME AS 학과, COUNT(*) 학생수
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPT_ID  = D.DEPT_ID 
GROUP BY DEPT_NAME

SELECT DNAME, COUNT(*), AVG(SAL), MAX(SAL), MIN(SAL)
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO 
GROUP BY DNAME

SELECT DEPT_NAME, COUNT(*), AVG(2026-YEAR_EMP), MAX(2026-YEAR_EMP)
FROM PROFESSOR P, DEPARTMENT D
WHERE P.DEPT_ID =D.DEPT_ID 
GROUP BY DEPT_NAME

SELECT DEPT_NAME, COUNT(*), AVG(2012-YEAR_EMP), MAX(2012-YEAR_EMP)
FROM PROFESSOR p , DEPARTMENT D
WHERE P.DEPT_ID = D.DEPT_ID 
AND AVG(2012-YEAR_EMP)>= 10
GROUP BY DEPT_NAME

SELECT DEPT_NAME, COUNT(*), AVG(2012-YEAR_EMP), MAX(2012-YEAR_EMP)
FROM PROFESSOR p , DEPARTMENT D
WHERE P.DEPT_ID = D.DEPT_ID 
GROUP BY DEPT_NAME
HAVING AVG(2012-YEAR_EMP)>=10

SELECT DNAME, COUNT(*), AVG(SAL), MAX(SAL), MIN(SAL)
FROM EMP E, DEPT D
WHERE E.DEPTNO =D.DEPTNO 
GROUP BY D.DNAME 
HAVING COUNT(*)>=5

SELECT *
FROM EMP
WHERE COMM IS NULL

SELECT *
FROM EMP
WHERE COMM IS NOT NULL

SELECT COUNT(*)
FROM EMP

SELECT TITLE
FROM COURSE
WHERE COURSE_ID IN (
	SELECT DISTINCT COURSE_ID
	FROM CLASS
	WHERE CLASSROOM='301호'
)

SELECT DISTINCT TITLE
FROM COURSE C1, CLASS C2
WHERE C1.COURSE_ID =C2.COURSE_ID 
AND C2.CLASSROOM ='301호'

SELECT TITLE
FROM COURSE
WHERE COURSE_ID NOT IN (
	SELECT DISTINCT COURSE_ID
	FROM CLASS
	WHERE YEAR=2012 AND SEMESTER=2
)

SELECT COURSE_ID, TITLE
FROM COURSE
MINUS
SELECT COURSE_ID
FROM CLASS
WHERE YEAR=2012 AND SEMESTER=2

SELECT *
FROM TAKES

CREATE OR REPLACE VIEW V_TAKES AS
	SELECT STU_ID, CLASS_ID
	FROM TAKES
	
SELECT *
FROM V_TAKES

CREATE OR REPLACE VIEW CS_STUDENT AS
	SELECT S.STU_ID, S.RESIDENT_ID, S.NAME, S.YEAR, S.ADDRESS, S.DEPT_ID
	FROM STUDENT S, DEPARTMENT D
	WHERE S.DEPT_ID=D.DEPT_ID
	AND D.DEPT_NAME='컴퓨터공학과'